name: 'revenue_intelligence'
version: '1.0.0'
config-version: 2
profile: 'revenue_intelligence'

model-paths: ['models']
macro-paths: ['macros']
target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  revenue_intelligence:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
